version: "2"
services:
    www:
        image: amarsingh3d/apache2.4-php7.2
        ports: 
            - "80:80"
        volumes:
            - ./DocumentRoot:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.6
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./MySQL_DATA:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent: