version: "2"
services:
    www:
        image: nu11secur1ty/suse-apache-docker-php7
        ports: 
            - "80:80"
        volumes:
            - ./DocumentRoot:/var/www/html/
        links:
            - db
            
        networks:
            - default
            
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#    db:
#        image: mysql:5.7
#        #image: mysql/mysql-server
#        ports: 
#            - "3306:3306"
#        environment:
#            MYSQL_DATABASE: myDb
#            MYSQL_USER: user
#            MYSQL_PASSWORD: test
#            MYSQL_ROOT_PASSWORD: test 
#        volumes:
#            - ./MySQL_DATA:/docker-entrypoint-initdb.d
#            - persistent:/var/lib/mysql
        networks:
            - default
   
   
   phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
